apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
spec:
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
        version: v1
    spec:
      containers:
      - name: auth-server
        image: 102132116425.dkr.ecr.ap-northeast-1.amazonaws.com/auth-server:v1
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
