server.port: 7001
server.error.include-message: always

spring.data.mongodb:
  auto-index-creation: true
  host: localhost
  port: 27017
  database: product-db

logging:
  level:
    root: INFO
    se.magnus.microservices: DEBUG
---
spring.profiles: docker

server.port: 8080
