apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        version: v2
    spec:
      containers:
      - name: pro
        image: 102132116425.dkr.ecr.ap-northeast-1.amazonaws.com/product-service:v2
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "400Mi"
