apiVersion: v1
kind: Service
metadata:
  name: nginx-servicespec:
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - targetPort: 80
      port: 80
      nodePort: 300080
